[parity]
chain = "./spec/spec.json"
base_path = "./nodes/validator/"

[network]
port = 30301
discovery = true
reserved_peers = "./nodes/reserved_peers"

[rpc]
disable = true

[websockets]
disable = true

[account]
unlock = [""]
password = ["./nodes/validator/node.pwd"]

[mining]
force_sealing = true
engine_signer = ""
reseal_on_txs = "none"

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"

